- name: Sync comment
  if: github.event.action == 'created' && steps.search.outputs.issue
  uses: atlassian/gajira-comment@v2.0.1
  with:
    issue: ${{ steps.search.outputs.issue }}
    comment: "${{ github.actor }} ${{ github.event.review.state || 'commented' }}:\n\n${{ github.event.comment.body || github.event.review.body }}\n\n${{ github.event.comment.html_url || github.event.review.html_url }}"
