name: cherry-picker

on:
  pull_request_target:
    types: [closed]
  issues:
    types: [closed, milestoned]

jobs:
  cherry-picker-on-milestoned:
    if: github.event.action == 'milestoned'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          egress-policy: audit
      - if: startsWith(github.event.issue.body, 'Forked from')
        name: Run cherrypicker on comment
        uses: bazelbuild/continuous-integration/actions/cherry_picker@35fc1da116a96631f83b45217ceb84e6ccee0106
        with:
          triggered-on: commented
          pr-number: ${{ github.event.issue.body }}
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          is-prod: True
      - if: startsWith(github.event.issue.body, '### Commit IDs')
        name: Run cherrypicker on demand
        uses: bazelbuild/continuous-integration/actions/cherry_picker@35fc1da116a96631f83b45217ceb84e6ccee0106
        with:
          triggered-on: ondemand
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}
          issue-body: ${{ github.event.issue.body }}
          is-prod: True
