name: Trigger an external notification for Staff Reports
on:
  issues:
    types: [opened]


jobs:
  issue-label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check trigger label
        if: ${{ !contains(github.event.issue.labels.*.name, 'Staff Report') }}
        run: |
            echo "No trigger label found, aborting workflow (not an error!)"
            exit 1
      - name: Set up Python3
        if: ${{ success() }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Checkout this repo
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Run the python3 script for this action
        if: ${{ success() }}
        env:
          REPORT_TOKEN: ${{ secrets.REPORT_TOKEN }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        # allowed to run 1 minute before killing
        timeout-minutes: 1
        run: |
          # external report to internal report
          pip3 install pyGithub
          pip3 install sh
          python3 issue-notify.py
